"""Build a self-contained static HTML policy explorer from a policies JSON file.

Usage:
    python scripts/build_explorer.py data/policies.json explorer/index.html

The output is a single HTML file with no external resources, suitable for
GitHub Pages or any static host. Policy data originates from crawled web
pages, so it is embedded as a JSON data island and rendered exclusively via
DOM textContent to prevent script injection.
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>OCP Heat Reuse Policy Explorer</title>
<style>
  :root {
    --green: #8dc63f; --dark: #1f2937; --muted: #6b7280;
    --bg: #f8fafc; --card: #ffffff; --border: #e5e7eb;
  }
  * { box-sizing: border-box; }
  body { margin: 0; font-family: "Segoe UI", system-ui, sans-serif; background: var(--bg); color: var(--dark); }
  header { background: var(--dark); color: #fff; padding: 20px 32px; }
  header h1 { margin: 0 0 4px; font-size: 22px; }
  header p { margin: 0; color: #cbd5e1; font-size: 13px; }
  header .badge { color: var(--green); font-weight: 600; }
  .controls { display: flex; flex-wrap: wrap; gap: 12px; padding: 16px 32px; background: var(--card); border-bottom: 1px solid var(--border); }
  .controls input, .controls select { padding: 8px 10px; border: 1px solid var(--border); border-radius: 6px; font-size: 14px; background: #fff; }
  .controls input[type="search"] { flex: 1 1 240px; }
  #count { padding: 8px 32px; color: var(--muted); font-size: 13px; }
  #list { display: grid; gap: 14px; padding: 0 32px 40px; grid-template-columns: repeat(auto-fill, minmax(340px, 1fr)); }
  .card { background: var(--card); border: 1px solid var(--border); border-radius: 10px; padding: 16px; display: flex; flex-direction: column; gap: 8px; }
  .card h2 { margin: 0; font-size: 15px; line-height: 1.35; }
  .card h2 a { color: var(--dark); text-decoration: none; }
  .card h2 a:hover { color: #4d7c0f; text-decoration: underline; }
  .meta { display: flex; flex-wrap: wrap; gap: 6px; font-size: 12px; }
  .chip { background: #eef2f7; border-radius: 999px; padding: 2px 10px; color: var(--dark); }
  .chip.score { background: var(--green); color: #1a2e05; font-weight: 600; }
  .summary { font-size: 13px; color: #374151; margin: 0; }
  .reqs { margin: 0; padding-left: 18px; font-size: 12.5px; color: #4b5563; }
  footer { padding: 16px 32px 32px; color: var(--muted); font-size: 12px; }
  .empty { padding: 40px 32px; color: var(--muted); }
</style>
</head>
<body>
<header>
  <h1>OCP Heat Reuse <span class="badge">Policy Explorer</span></h1>
  <p>Data center heat reuse laws and regulations discovered by PolicyPulse.
     Read-only snapshot; generated __GENERATED_AT__.</p>
</header>
<div class="controls">
  <input id="q" type="search" placeholder="Search name, summary, jurisdiction...">
  <select id="jurisdiction"><option value="">All jurisdictions</option></select>
  <select id="ptype"><option value="">All types</option></select>
  <select id="minscore">
    <option value="0">Any relevance</option>
    <option value="5">Relevance 5+</option>
    <option value="7">Relevance 7+</option>
    <option value="9">Relevance 9+</option>
  </select>
  <select id="sort">
    <option value="score">Sort: relevance</option>
    <option value="name">Sort: name</option>
    <option value="jurisdiction">Sort: jurisdiction</option>
    <option value="date">Sort: effective date</option>
  </select>
</div>
<div id="count"></div>
<div id="list"></div>
<footer>
  Generated by PolicyPulse (OCP-CE-HR-Policy-Searcher). Front end concept by the
  Uppsala University thesis team: Valdemar Jeirud, Elliot Loewenhielm, David Fors,
  and Alexander Stephanson.
</footer>
<script type="application/json" id="policy-data">__POLICY_DATA__</script>
<script>
"use strict";
const policies = JSON.parse(document.getElementById("policy-data").textContent);

function safeUrl(u) {
  try {
    const parsed = new URL(u);
    if (parsed.protocol === "http:" || parsed.protocol === "https:") return parsed.href;
  } catch (e) { /* fall through */ }
  return null;
}

function fillSelect(id, values) {
  const sel = document.getElementById(id);
  for (const v of [...new Set(values)].sort()) {
    const opt = document.createElement("option");
    opt.value = v; opt.textContent = v;
    sel.appendChild(opt);
  }
}
fillSelect("jurisdiction", policies.map(p => p.jurisdiction).filter(Boolean));
fillSelect("ptype", policies.map(p => p.policy_type).filter(Boolean));

function render() {
  const q = document.getElementById("q").value.toLowerCase();
  const jur = document.getElementById("jurisdiction").value;
  const typ = document.getElementById("ptype").value;
  const min = Number(document.getElementById("minscore").value);
  const sort = document.getElementById("sort").value;

  let rows = policies.filter(p =>
    (!jur || p.jurisdiction === jur) &&
    (!typ || p.policy_type === typ) &&
    ((p.relevance_score ?? 0) >= min) &&
    (!q || [p.policy_name, p.summary, p.jurisdiction, p.bill_number]
      .some(f => (f || "").toLowerCase().includes(q)))
  );

  const cmp = {
    score: (a, b) => (b.relevance_score ?? 0) - (a.relevance_score ?? 0),
    name: (a, b) => (a.policy_name || "").localeCompare(b.policy_name || ""),
    jurisdiction: (a, b) => (a.jurisdiction || "").localeCompare(b.jurisdiction || ""),
    date: (a, b) => (b.effective_date || "").localeCompare(a.effective_date || ""),
  }[sort];
  rows.sort(cmp);

  document.getElementById("count").textContent =
    rows.length + " of " + policies.length + " policies";

  const list = document.getElementById("list");
  list.replaceChildren();
  if (!rows.length) {
    const div = document.createElement("div");
    div.className = "empty";
    div.textContent = "No policies match the current filters.";
    list.appendChild(div);
    return;
  }
  for (const p of rows) {
    const card = document.createElement("div");
    card.className = "card";

    const h2 = document.createElement("h2");
    const href = safeUrl(p.url);
    if (href) {
      const a = document.createElement("a");
      a.href = href; a.target = "_blank"; a.rel = "noopener noreferrer";
      a.textContent = p.policy_name || "(unnamed policy)";
      h2.appendChild(a);
    } else {
      h2.textContent = p.policy_name || "(unnamed policy)";
    }
    card.appendChild(h2);

    const meta = document.createElement("div");
    meta.className = "meta";
    const chips = [
      [p.jurisdiction, ""],
      [p.policy_type, ""],
      [p.effective_date ? "Effective " + p.effective_date : null, ""],
      [p.bill_number, ""],
      [p.relevance_score != null ? "Relevance " + p.relevance_score + "/10" : null, "score"],
    ];
    for (const [text, extra] of chips) {
      if (!text) continue;
      const chip = document.createElement("span");
      chip.className = ("chip " + extra).trim();
      chip.textContent = text;
      meta.appendChild(chip);
    }
    card.appendChild(meta);

    if (p.summary) {
      const s = document.createElement("p");
      s.className = "summary";
      s.textContent = p.summary;
      card.appendChild(s);
    }
    if (Array.isArray(p.key_requirements) && p.key_requirements.length) {
      const ul = document.createElement("ul");
      ul.className = "reqs";
      for (const r of p.key_requirements.slice(0, 4)) {
        const li = document.createElement("li");
        li.textContent = r;
        ul.appendChild(li);
      }
      card.appendChild(ul);
    }
    list.appendChild(card);
  }
}

for (const id of ["q", "jurisdiction", "ptype", "minscore", "sort"]) {
  document.getElementById(id).addEventListener("input", render);
}
render();
</script>
</body>
</html>
"""


def build_explorer_html(policies: list[dict], generated_at: str | None = None) -> str:
    """Render the static explorer page for the given policy records."""
    if generated_at is None:
        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    # Escape "</" so hostile policy text cannot close the data-island script
    # tag. "\/" is a valid JSON escape for "/", so the island parses unchanged.
    data = json.dumps(policies, ensure_ascii=True).replace("</", "<\\/")
    return (
        PAGE_TEMPLATE
        .replace("__GENERATED_AT__", generated_at)
        .replace("__POLICY_DATA__", data)
    )


def main(argv: list[str]) -> None:
    if len(argv) != 2:
        print("Usage: python scripts/build_explorer.py <policies.json> <output.html>")
        raise SystemExit(2)
    input_path, output_path = Path(argv[0]), Path(argv[1])
    if not input_path.exists():
        print(f"Input file not found: {input_path}")
        raise SystemExit(1)

    policies = json.loads(input_path.read_text(encoding="utf-8"))
    if not isinstance(policies, list):
        print(f"Expected a JSON array of policies in {input_path}")
        raise SystemExit(1)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_explorer_html(policies), encoding="utf-8")
    print(f"Wrote {output_path} ({len(policies)} policies)")


if __name__ == "__main__":
    main(sys.argv[1:])
